name: Auto-Update FFlags
on:
  schedule:
    - cron: '* * * * *'
jobs:
  update-fflags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.sshprivate }}
      - name: Set git email
        run: git config --global user.email ${{ secrets.gitemail }}
      - name: Set git user
        run: git config --global user.name ${{ secrets.gituser }}
      - name: Clone repo
        run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
      - name: Run nodejs file
        id: update_fflags
        run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FFlag\"]}]' /FFlags/ClientAppSettings.json"
      - name: Add changed file, commit and push to repo
        continue-on-error: true
        run: |
          git add FFlags/ClientAppSettings.json
          git pull
          git commit -a -m "Updated FFlags"
          git push origin main
  update-fflags-fints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.sshprivate }}
      - name: Set git email
        run: git config --global user.email ${{ secrets.gitemail }}
      - name: Set git user
        run: git config --global user.name ${{ secrets.gituser }}
      - name: Clone repo
        run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
      - name: Run nodejs file
        id: update_fflags
        run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FFlag\", \"FInt\"]}]' \"/FInt and FFlag/ClientAppSettings.json\""
      - name: Add changed file, commit and push to repo
        continue-on-error: true
        run: |
          git add "FInt and FFlag/ClientAppSettings.json"
          git pull
          git commit -a -m "Updated FFlags"
          git push origin main
  update-fflags-fpsunlock:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.sshprivate }}
      - name: Set git email
        run: git config --global user.email ${{ secrets.gitemail }}
      - name: Set git user
        run: git config --global user.name ${{ secrets.gituser }}
      - name: Clone repo
        run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
      - name: Run nodejs file
        id: update_fflags
        run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FFlag\"]},{\"tbl\": \"values\", \"values\": [500]}]' \"/FFlag and FPS Unlock/ClientAppSettings.json\""
      - name: Add changed file, commit and push to repo
        continue-on-error: true
        run: |
          git add "FFlag and FPS Unlock/ClientAppSettings.json"
          git pull
          git commit -a -m "Updated FFlags"
          git push origin main
  update-fflags-fints-fstrings:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3.5.2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.5.2
        - name: Setup SSH key
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.sshprivate }}
        - name: Set git email
          run: git config --global user.email ${{ secrets.gitemail }}
        - name: Set git user
          run: git config --global user.name ${{ secrets.gituser }}
        - name: Clone repo
          run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
        - name: Run nodejs file
          id: update_fflags
          run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FFlag\", \"FInt\", \"FString\"]}]' /All/ClientAppSettings.json"
        - name: Add changed file, commit and push to repo
          continue-on-error: true
          run: |
            git add All/ClientAppSettings.json
            git pull
          git commit -a -m "Updated FFlags"
            git push origin main
  update-fflags-fstrings:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3.5.2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.5.2
        - name: Setup SSH key
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.sshprivate }}
        - name: Set git email
          run: git config --global user.email ${{ secrets.gitemail }}
        - name: Set git user
          run: git config --global user.name ${{ secrets.gituser }}
        - name: Clone repo
          run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
        - name: Run nodejs file
          id: update_fflags
          run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FFlag\", \"FString\"]}]' \"/FString and FFlag/ClientAppSettings.json\""
        - name: Add changed file, commit and push to repo
          continue-on-error: true
          run: |
            git add "FString and FFlag/ClientAppSettings.json"
            git pull
          git commit -a -m "Updated FFlags"
            git push origin main
  update-fints-fstrings:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3.5.2
        - name: Setup Node.js environment
          uses: actions/setup-node@v2.5.2
        - name: Setup SSH key
          uses: webfactory/ssh-agent@v0.8.0
          with:
            ssh-private-key: ${{ secrets.sshprivate }}
        - name: Set git email
          run: git config --global user.email ${{ secrets.gitemail }}
        - name: Set git user
          run: git config --global user.name ${{ secrets.gituser }}
        - name: Clone repo
          run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
        - name: Run nodejs file
          id: update_fflags
          run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FInt\", \"FString\"]}]' \"/FString and FInt/ClientAppSettings.json\""
        - name: Add changed file, commit and push to repo
          continue-on-error: true
          run: |
            git add "FString and FInt/ClientAppSettings.json"
            git pull
          git commit -a -m "Updated FFlags"
            git push origin main
  update-fints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.sshprivate }}
      - name: Set git email
        run: git config --global user.email ${{ secrets.gitemail }}
      - name: Set git user
        run: git config --global user.name ${{ secrets.gituser }}
      - name: Clone repo
        run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
      - name: Run nodejs file
        id: update_fflags
        run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FInts\"]}]' /FInt/ClientAppSettings.json"
      - name: Add changed file, commit and push to repo
        continue-on-error: true
        run: |
          git add FInt/ClientAppSettings.json
          git pull
          git commit -a -m "Updated FFlags"
          git push origin main
  update-fstrings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.sshprivate }}
      - name: Set git email
        run: git config --global user.email ${{ secrets.gitemail }}
      - name: Set git user
        run: git config --global user.name ${{ secrets.gituser }}
      - name: Clone repo
        run: git clone git@github.com:fheahdythdr/rco-but-it-uses-different-fflags
      - name: Run nodejs file
        id: update_fflags
        run: "node ./workflow-files/update '[{\"tbl\": \"includes\", \"values\": [\"FString\"]}]' /FString/ClientAppSettings.json"
      - name: Add changed file, commit and push to repo
        continue-on-error: true
        run: |
          git add FString/ClientAppSettings.json
          git pull
          git commit -a -m "Updated FFlags"
          git push origin main
